global:
  message: Welcome to global Microservices Environment!!
logging:
 level:
  root: INFO
 management:
  endpoints:
   web:
    exposure:
     include: health,Infi,refresh
  endpoint:
      health:
       show-details: always
  
